/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyReposIndexRouteImport } from './routes/my-repos/index'
import { Route as InspectIndexRouteImport } from './routes/inspect/index'
import { Route as DestinationIndexRouteImport } from './routes/destination/index'
import { Route as ConfirmIndexRouteImport } from './routes/confirm/index'
import { Route as CloningIndexRouteImport } from './routes/cloning/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReposIndexRoute = MyReposIndexRouteImport.update({
  id: '/my-repos/',
  path: '/my-repos/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectIndexRoute = InspectIndexRouteImport.update({
  id: '/inspect/',
  path: '/inspect/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationIndexRoute = DestinationIndexRouteImport.update({
  id: '/destination/',
  path: '/destination/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmIndexRoute = ConfirmIndexRouteImport.update({
  id: '/confirm/',
  path: '/confirm/',
  getParentRoute: () => rootRouteImport,
} as any)
const CloningIndexRoute = CloningIndexRouteImport.update({
  id: '/cloning/',
  path: '/cloning/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/cloning/': typeof CloningIndexRoute
  '/confirm/': typeof ConfirmIndexRoute
  '/destination/': typeof DestinationIndexRoute
  '/inspect/': typeof InspectIndexRoute
  '/my-repos/': typeof MyReposIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseIndexRoute
  '/cloning': typeof CloningIndexRoute
  '/confirm': typeof ConfirmIndexRoute
  '/destination': typeof DestinationIndexRoute
  '/inspect': typeof InspectIndexRoute
  '/my-repos': typeof MyReposIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/cloning/': typeof CloningIndexRoute
  '/confirm/': typeof ConfirmIndexRoute
  '/destination/': typeof DestinationIndexRoute
  '/inspect/': typeof InspectIndexRoute
  '/my-repos/': typeof MyReposIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse/'
    | '/cloning/'
    | '/confirm/'
    | '/destination/'
    | '/inspect/'
    | '/my-repos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/cloning'
    | '/confirm'
    | '/destination'
    | '/inspect'
    | '/my-repos'
  id:
    | '__root__'
    | '/'
    | '/browse/'
    | '/cloning/'
    | '/confirm/'
    | '/destination/'
    | '/inspect/'
    | '/my-repos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  CloningIndexRoute: typeof CloningIndexRoute
  ConfirmIndexRoute: typeof ConfirmIndexRoute
  DestinationIndexRoute: typeof DestinationIndexRoute
  InspectIndexRoute: typeof InspectIndexRoute
  MyReposIndexRoute: typeof MyReposIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-repos/': {
      id: '/my-repos/'
      path: '/my-repos'
      fullPath: '/my-repos/'
      preLoaderRoute: typeof MyReposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/': {
      id: '/inspect/'
      path: '/inspect'
      fullPath: '/inspect/'
      preLoaderRoute: typeof InspectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/': {
      id: '/destination/'
      path: '/destination'
      fullPath: '/destination/'
      preLoaderRoute: typeof DestinationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm/': {
      id: '/confirm/'
      path: '/confirm'
      fullPath: '/confirm/'
      preLoaderRoute: typeof ConfirmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloning/': {
      id: '/cloning/'
      path: '/cloning'
      fullPath: '/cloning/'
      preLoaderRoute: typeof CloningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  CloningIndexRoute: CloningIndexRoute,
  ConfirmIndexRoute: ConfirmIndexRoute,
  DestinationIndexRoute: DestinationIndexRoute,
  InspectIndexRoute: InspectIndexRoute,
  MyReposIndexRoute: MyReposIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
